[args-or-stdin] Print to stderr (not stdout)

diff --git a/bin/args-or-stdin b/bin/args-or-stdin
--- a/bin/args-or-stdin
+++ b/bin/args-or-stdin
@@ -12,7 +12,7 @@ if [ $# -ne 0 ] ; then
 elif [[ -p /dev/stdin ]] ; then
   input="$(cat -)"
 else
-  echo "Error: received no arguments or stdin."
+  echo "Error: received no arguments or stdin." >&2
   exit 1
 fi
 
