[hpr] Disallow  attempting to open a PR on safe or main

diff --git a/bin/hpr b/bin/hpr
--- a/bin/hpr
+++ b/bin/hpr
@@ -6,6 +6,11 @@
 
 set -euo pipefail # exit on any error, don't allow undefined variables, pass errors through pipes
 
+if on-safe-or-main ; then
+  echo "You can't open a PR from $(branch)!"
+  exit 1
+fi
+
 # git push force
 gpf
 
