[blue]/[red]: Check whether script was called with arguments first
I was having issues when `rlint` would fail in a git pre-push hook.

diff --git a/bin/red b/bin/red
--- a/bin/red
+++ b/bin/red
@@ -10,10 +10,13 @@ set -euo pipefail # exit on any error, don't allow undefined variables, pipes do
 
 input=""
 
-if [[ -p /dev/stdin ]]; then
+if [ $# -ne 0 ] ; then
+  input="${@}"
+elif [[ -p /dev/stdin ]] ; then
   input="$(cat -)"
 else
-  input="${@}"
+  echo "Error: received no arguments or stdin."
+  exit 1
 fi
 
 echo "[1;31m$input[0m"
