[tsc] Add set -e so that the generated scripts will exit on any error

diff --git a/bin/tsc b/bin/tsc
--- a/bin/tsc
+++ b/bin/tsc
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# # [t]ouch a file and open it in editor (which used to be [s]ublime) and [c]hmod it to executable
+# [t]ouch a file and open it in editor (which used to be [s]ublime) and [c]hmod it to executable
 
 set -euo pipefail # exit on any error, don't allow undefined variables, pipes don't swallow errors
 
@@ -13,5 +13,5 @@ chmod +x "$file_path"
 cat <<EOF >> "$file_path"
 #!/usr/bin/env bash
 
-set -uo pipefail # don't allow undefined variables, pipes don't swallow errors
+set -euo pipefail # exit on any error, don't allow undefined variables, pipes don't swallow errors
 EOF
